#' @title Get MSIP isotopomer probability as SummarizedExperiment
#' @description Extract isotopomer quantification (probabilities) from
#' \code{object@advancedAna$MSIP$isotopomer_data} and return a
#' \code{\link[SummarizedExperiment]{SummarizedExperiment}} with columns as
#' \code{sample.source} and rows as isotopomers.
#'
#' @param object A \code{MSdev} object with \code{object@advancedAna$MSIP$isotopomer_data}
#'   generated by \code{\link{MSIP_get_isotopomer_data}}.
#'
#' @return A \code{SummarizedExperiment} with one assay \code{"probability"}.
#'   \itemize{
#'     \item \code{colData}: \code{sample.source}, \code{group}
#'     \item \code{rowData}: \code{isotopomer_id}, \code{compound_id},
#'       \code{compound_name}, \code{isotopologue_id}, \code{isotopologue_form},
#'       \code{isotopome_form}, \code{label.isotopomer}, \code{label.isotopologue},
#'       \code{isotopomer_average_mix}
#'   }
#' @export
get_MSIP_Isotopomer_SE <- function(object) {
  `%||%` <- function(a, b) if (!is.null(a)) a else b

  if (is.null(object@advancedAna$MSIP$isotopomer_data)) {
    stop("No MSIP isotopomer data found in object@advancedAna$MSIP$isotopomer_data. ",
         "Run MSIP_get_isotopomer_data() first.")
  }

  isotopomer_data <- object@advancedAna$MSIP$isotopomer_data
  if (!is.list(isotopomer_data) || length(isotopomer_data) == 0) {
    stop("object@advancedAna$MSIP$isotopomer_data is empty.")
  }

  sample.info <- tryCatch({
    as.data.frame(object@sampleInfo)
  }, error = function(e) NULL)

  compound_table <- tryCatch({
    object@advancedAna$MSIP$compound_table
  }, error = function(e) NULL)
  compound_name_map <- NULL
  if (!is.null(compound_table) &&
      is.data.frame(compound_table) &&
      nrow(compound_table) > 0 &&
      "compound_id" %in% colnames(compound_table)) {
    name_col <- intersect(c("name", "compound_name"), colnames(compound_table))[1]
    if (!is.na(name_col) && !is.null(name_col)) {
      compound_name_map <- as.character(compound_table[[name_col]])
      names(compound_name_map) <- as.character(compound_table$compound_id)
    }
  }

  # Collect all sample sources present in the stored matrices
  sample.sources <- unique(unlist(lapply(isotopomer_data, function(mat) {
    if (is.null(mat)) return(character())
    colnames(mat) %||% character()
  })))
  sample.sources <- as.character(sample.sources)
  if (length(sample.sources) == 0) {
    stop("No sample.source columns found in object@advancedAna$MSIP$isotopomer_data matrices.")
  }

  # colData: sample.source + group (mapped from sample.info if available)
  group.val <- rep(NA_character_, length(sample.sources))
  if (!is.null(sample.info) &&
      nrow(sample.info) > 0 &&
      "sample.source" %in% colnames(sample.info) &&
      "group" %in% colnames(sample.info)) {
    group.val <- vapply(sample.sources, function(ss) {
      g <- unique(as.character(sample.info$group[sample.info$sample.source %in% ss]))
      g <- g[!is.na(g) & nzchar(g)]
      if (length(g) == 0) return(NA_character_)
      paste(g, collapse = ";")
    }, character(1))
  }

  cda <- S4Vectors::DataFrame(
    sample.source = sample.sources,
    group = group.val,
    row.names = sample.sources
  )

  # Helper: get isotopomer meta from a single MSIPCoreData
  .extract_isotopomer_meta <- function(msip.core) {
    if (is.null(msip.core)) return(NULL)
    if (is.null(msip.core@Solve$MSIPIsotopomerMap)) return(NULL)
    im <- msip.core@Solve$MSIPIsotopomerMap
    if (S4Vectors::isEmpty(im)) return(NULL)

    prob <- im@isotopomer.probability
    if (length(prob) == 0) return(NULL)

    iso_names <- names(prob)
    if (is.null(iso_names) || any(!nzchar(iso_names))) {
      iso_names <- paste0("isotopomer_", seq_along(prob))
    }

    sets <- im@solve$isotopomer.set
    if (is.null(sets)) sets <- list()

    isotopomer_mix <- rep(NA_real_, length(iso_names))
    if (length(sets) > 0) {
      set_sizes <- lengths(sets)
      for (set_nm in names(sets)) {
        members <- sets[[set_nm]]
        members <- as.character(members)
        idx <- iso_names %in% members
        if (any(idx)) {
          isotopomer_mix[idx] <- as.numeric(set_sizes[[set_nm]])
        }
      }
    }

    list(
      iso_names = iso_names,
      prob = as.numeric(prob),
      isotopomer_mix = isotopomer_mix
    )
  }

  # Build master row index (compound_id + isotopologue_form + isotopomer name)
  rows <- list()
  for (compound_id in names(isotopomer_data)) {
    mat <- isotopomer_data[[compound_id]]
    if (is.null(mat) || !is.matrix(mat)) next

    iso_forms <- rownames(mat) %||% character()
    for (iso_form in iso_forms) {
      # find one representative msip.core for meta (first non-null)
      msip.core.rep <- NULL
      for (ss in intersect(colnames(mat) %||% character(), sample.sources)) {
        x <- mat[iso_form, ss][[1]]
        if (!is.null(x)) {
          msip.core.rep <- x
          break
        }
      }

      meta <- .extract_isotopomer_meta(msip.core.rep)
      if (is.null(meta)) next

      isotopomer_id <- paste0(compound_id, "_", meta$iso_names)
      isotopologue_id <- paste0(compound_id, "_", iso_form)
      compound_name <- if (!is.null(compound_name_map) && compound_id %in% names(compound_name_map)) {
        compound_name_map[[compound_id]]
      } else {
        NA_character_
      }

      # isotopologue form is like "[13]C1", extract trailing count -> 1
      iso_form_num <- suppressWarnings(as.integer(sub(".*?([0-9]+)$", "\\1", iso_form)))
      if (is.na(iso_form_num)) iso_form_num <- NA_integer_
      isotopologue_mplus <- if (is.na(iso_form_num)) NA_character_ else paste0("M+", iso_form_num)
      # label isotopomer should align with isotopomer_id form
      label_isotopomer <- if (is.na(compound_name)) {
        rep(NA_character_, length(meta$iso_names))
      } else {
        paste0(compound_name, "_", meta$iso_names)
      }
      label_isotopologue <- if (is.na(compound_name) || is.na(isotopologue_mplus)) {
        rep(NA_character_, length(meta$iso_names))
      } else {
        rep(paste0(compound_name, "_", isotopologue_mplus), length(meta$iso_names))
      }

      rows[[paste0(compound_id, "::", iso_form)]] <- data.frame(
        isotopomer_id = isotopomer_id,
        compound_id = compound_id,
        compound_name = compound_name,
        isotopologue_id = isotopologue_id,
        isotopologue_form = iso_form,
        iso_name = meta$iso_names,
        label.isotopomer = label_isotopomer,
        label.isotopologue = label_isotopologue,
        stringsAsFactors = FALSE
      )
    }
  }

  if (length(rows) == 0) {
    stop("No solved isotopomer probabilities found in object@advancedAna$MSIP$isotopomer_data.")
  }

  row.df <- do.call(rbind, rows)
  if (anyDuplicated(row.df$isotopomer_id)) {
    warning("Duplicated isotopomer_id detected (same compound_id + isotopomer name across isotopologues). ",
            "Making rownames unique with make.unique().")
    row.df$isotopomer_id <- make.unique(row.df$isotopomer_id)
  }
  rownames(row.df) <- row.df$isotopomer_id

  # assay matrix: probabilities aligned to master rows
  prob.mat <- matrix(NA_real_, nrow = nrow(row.df), ncol = length(sample.sources),
                     dimnames = list(row.df$isotopomer_id, sample.sources))
  mix.mat <- matrix(NA_real_, nrow = nrow(row.df), ncol = length(sample.sources),
                    dimnames = list(row.df$isotopomer_id, sample.sources))

  for (compound_id in names(isotopomer_data)) {
    mat <- isotopomer_data[[compound_id]]
    if (is.null(mat) || !is.matrix(mat)) next
    iso_forms <- rownames(mat) %||% character()

    for (iso_form in iso_forms) {
      for (ss in intersect(colnames(mat) %||% character(), sample.sources)) {
        msip.core <- mat[iso_form, ss][[1]]
        meta <- .extract_isotopomer_meta(msip.core)
        if (is.null(meta)) next

        row_ids <- paste0(compound_id, "_", meta$iso_names)
        keep <- row_ids %in% rownames(prob.mat)
        if (any(keep)) {
          prob.mat[row_ids[keep], ss] <- meta$prob[keep]
          mix.mat[row_ids[keep], ss] <- meta$isotopomer_mix[keep]
        }
      }
    }
  }

  isotopomer_average_mix <- rowMeans(mix.mat, na.rm = TRUE)
  isotopomer_average_mix[is.nan(isotopomer_average_mix)] <- NA_real_

  # keep only requested rowData columns
  rda <- S4Vectors::DataFrame(
    isotopomer_id = row.df$isotopomer_id,
    compound_id = row.df$compound_id,
    compound_name = row.df$compound_name,
    isotopologue_id = row.df$isotopologue_id,
    isotopologue_form = row.df$isotopologue_form,
    isotopome_form = row.df$iso_name,
    label.isotopomer = row.df$label.isotopomer,
    label.isotopologue = row.df$label.isotopologue,
    isotopomer_average_mix = isotopomer_average_mix,
    row.names = row.df$isotopomer_id
  )

  SummarizedExperiment::SummarizedExperiment(
    assays = list(probability = prob.mat),
    rowData = rda,
    colData = cda
  )
}


#' @title Get MSIP isotopologue data as SummarizedExperiment
#' @description Build a single isotopologue-level
#' \code{\link[SummarizedExperiment]{SummarizedExperiment}} from
#' \code{object@advancedAna$MSIP$isotopologue_data}. If isotopologue data is not
#' present yet, this function constructs it from current xcms annotations via
#' \code{\link{get_MSIPIsotopologueData}}.
#'
#' The returned object keeps \code{sample.source} as columns and
#' isotopologue IDs (compound + isotopologue form) as rows, similar to
#' \code{\link{get_MSIP_Isotopomer_SE}}.
#'
#' @param object A \code{MSdev} object.
#' @param ... Additional arguments passed to \code{\link{get_MSIPIsotopologueData}}
#'   when isotopologue data needs to be built.
#'
#' @return A \code{SummarizedExperiment} with assays:
#' \itemize{
#'   \item \code{ratio} (default assay; merged from positive/negative)
#'   \item \code{ratio.positive}
#'   \item \code{ratio.negative}
#'   \item \code{intensity.positive}
#'   \item \code{intensity.negative}
#'   \item \code{purity.positive}
#'   \item \code{purity.negative}
#' }
#' Row metadata is taken from per-compound isotopologue objects and includes
#' \code{isotopologue_id}, \code{compound_id}, \code{compound_name},
#' \code{isotopologue_form}, and \code{label.isotopologue} when available.
#' Additional derived columns:
#' \itemize{
#'   \item \code{polarity}: \code{"0"}, \code{"1"}, or \code{"0;1"} depending on which
#'   of \code{ratio.negative}/\code{ratio.positive} is present for that isotopologue row.
#'   \item \code{similarity}: cosine similarity between the compound-level positive and
#'   negative ratio matrices (all isotopologues and all sample.sources).
#' }
#' Column metadata contains \code{sample.source} and \code{group}.
#' @export
get_MSIP_Isotopologue_SE <- function(object, ...) {
  `%||%` <- function(a, b) if (!is.null(a)) a else b

  iso.list <- tryCatch(
    object@advancedAna$MSIP$isotopologue_data,
    error = function(e) NULL
  )
  if (is.null(iso.list) || !is.list(iso.list) || !length(iso.list)) {
    iso.list <- get_MSIPIsotopologueData(object, ...)
  }
  if (!is.list(iso.list) || !length(iso.list)) {
    stop("No isotopologue data found. ",
         "Run MSIP_xcms_processing.targeted() first, then build isotopologue data.")
  }

  # Keep only valid SummarizedExperiment-like isotopologue entries.
  iso.list <- Filter(function(x) methods::is(x, "SummarizedExperiment"), iso.list)
  if (!length(iso.list)) {
    stop("object@advancedAna$MSIP$isotopologue_data has no valid SummarizedExperiment entries.")
  }

  # Union sample.source across compounds.
  sample.sources <- unique(unlist(lapply(iso.list, function(sei) {
    cda <- tryCatch(as.data.frame(SummarizedExperiment::colData(sei)), error = function(e) NULL)
    if (is.null(cda) || !nrow(cda)) return(character())
    if ("sample.source" %in% colnames(cda)) {
      as.character(cda$sample.source)
    } else {
      rownames(cda) %||% character()
    }
  })))
  sample.sources <- as.character(sample.sources)
  sample.sources <- sample.sources[!is.na(sample.sources) & nzchar(sample.sources)]
  if (!length(sample.sources)) {
    stop("No sample.source columns found in isotopologue data.")
  }

  sample.info <- tryCatch(as.data.frame(object@sampleInfo), error = function(e) NULL)
  group.val <- rep(NA_character_, length(sample.sources))
  if (!is.null(sample.info) &&
      nrow(sample.info) > 0 &&
      all(c("sample.source", "group") %in% colnames(sample.info))) {
    group.val <- vapply(sample.sources, function(ss) {
      g <- unique(as.character(sample.info$group[sample.info$sample.source %in% ss]))
      g <- g[!is.na(g) & nzchar(g)]
      if (!length(g)) return(NA_character_)
      paste(g, collapse = ";")
    }, character(1))
  }
  cda <- S4Vectors::DataFrame(
    sample.source = sample.sources,
    group = group.val,
    row.names = sample.sources
  )

  # Build master rowData table by stacking each compound's rowData.
  row.list <- list()
  for (nm in names(iso.list)) {
    sei <- iso.list[[nm]]
    rda <- tryCatch(as.data.frame(SummarizedExperiment::rowData(sei)), error = function(e) NULL)
    if (is.null(rda) || !nrow(rda)) next
    if (!("isotopologue_id" %in% colnames(rda))) {
      rid <- rownames(rda)
      if (is.null(rid) || any(!nzchar(rid))) {
        rid <- paste0(nm, "_", seq_len(nrow(rda)))
      }
      rda$isotopologue_id <- rid
    }
    if (is.null(rownames(rda)) || any(!nzchar(rownames(rda)))) {
      rownames(rda) <- rda$isotopologue_id
    }
    row.list[[length(row.list) + 1L]] <- rda
  }
  if (!length(row.list)) {
    stop("No isotopologue rows found in isotopologue data.")
  }

  row.df <- do.call(rbind, row.list)
  row.df$isotopologue_id <- as.character(row.df$isotopologue_id)
  if (anyDuplicated(row.df$isotopologue_id)) {
    warning("Duplicated isotopologue_id detected; using make.unique() for row names.")
    row.df$isotopologue_id <- make.unique(row.df$isotopologue_id)
  }
  rownames(row.df) <- row.df$isotopologue_id

  # NOTE: keep a single merged ratio assay as the default (first assay),
  # but also retain polarity-specific ratio assays.
  assay.names <- c(
    "ratio",
    "ratio.positive", "ratio.negative",
    "intensity.positive", "intensity.negative",
    "purity.positive", "purity.negative"
  )
  assays.out <- setNames(
    lapply(assay.names, function(nm) {
      matrix(NA_real_, nrow = nrow(row.df), ncol = length(sample.sources),
             dimnames = list(row.df$isotopologue_id, sample.sources))
    }),
    assay.names
  )

  # Fill assay matrices from each per-compound isotopologue object.
  for (sei in iso.list) {
    this.rda <- tryCatch(as.data.frame(SummarizedExperiment::rowData(sei)), error = function(e) NULL)
    if (is.null(this.rda) || !nrow(this.rda)) next

    this.row_id <- this.rda$isotopologue_id %||% rownames(this.rda)
    this.row_id <- as.character(this.row_id)
    keep.row <- this.row_id %in% rownames(row.df)
    if (!any(keep.row)) next

    col.map <- tryCatch(as.data.frame(SummarizedExperiment::colData(sei)), error = function(e) NULL)
    if (is.null(col.map) || !nrow(col.map)) {
      this.sources <- colnames(SummarizedExperiment::assay(sei, 1))
    } else if ("sample.source" %in% colnames(col.map)) {
      this.sources <- as.character(col.map$sample.source)
    } else {
      this.sources <- rownames(col.map)
    }
    this.sources <- as.character(this.sources)

    available.assays <- names(SummarizedExperiment::assays(sei))

    # ---- ratio.positive / ratio.negative (kept) ----
    for (an in intersect(c("ratio.positive", "ratio.negative"), available.assays)) {
      m <- SummarizedExperiment::assay(sei, an)
      if (is.null(m) || !nrow(m) || !ncol(m)) next

      row.hit <- match(this.row_id[keep.row], rownames(m))
      row.ok <- !is.na(row.hit)
      if (!any(row.ok)) next

      col.hit <- match(sample.sources, this.sources)
      col.ok <- !is.na(col.hit)
      if (!any(col.ok)) next

      src.values <- m[row.hit[row.ok], col.hit[col.ok], drop = FALSE]
      assays.out[[an]][this.row_id[keep.row][row.ok], sample.sources[col.ok]] <- src.values
    }

    # ---- other assays (intensity/purity, polarity-specific) ----
    other_assays <- c("intensity.positive", "intensity.negative", "purity.positive", "purity.negative")
    for (an in intersect(other_assays, available.assays)) {
      m <- SummarizedExperiment::assay(sei, an)
      if (is.null(m) || !nrow(m) || !ncol(m)) next

      # Align rows by isotopologue_id and columns by sample.source.
      row.hit <- match(this.row_id[keep.row], rownames(m))
      row.ok <- !is.na(row.hit)
      if (!any(row.ok)) next

      col.hit <- match(sample.sources, this.sources)
      col.ok <- !is.na(col.hit)
      if (!any(col.ok)) next

      src.values <- m[row.hit[row.ok], col.hit[col.ok], drop = FALSE]
      assays.out[[an]][this.row_id[keep.row][row.ok], sample.sources[col.ok]] <- src.values
    }
  }

  # ---- build merged ratio from ratio.positive/ratio.negative ----
  rp <- assays.out[["ratio.positive"]]
  rn <- assays.out[["ratio.negative"]]
  rm <- rp
  both <- !is.na(rp) & !is.na(rn)
  rm[is.na(rm)] <- rn[is.na(rm)]
  rm[both] <- (rp[both] + rn[both]) / 2
  assays.out[["ratio"]] <- rm

  # ---- fill all NA with 0 (per review) ----
  for (nm in names(assays.out)) {
    x <- assays.out[[nm]]
    x[is.na(x)] <- 0
    assays.out[[nm]] <- x
  }

  keep.cols <- c(
    "isotopologue_id", "compound_id", "compound_name",
    "isotopologue_form", "label.isotopologue"
  )
  keep.cols <- intersect(keep.cols, colnames(row.df))
  rda.out <- S4Vectors::DataFrame(
    row.df[, keep.cols, drop = FALSE],
    row.names = row.df$isotopologue_id
  )
  if (!("isotopologue_id" %in% colnames(rda.out))) {
    rda.out$isotopologue_id <- row.df$isotopologue_id
  }

  # ---- derived rowData: polarity + similarity ----
  # polarity is determined by whether the isotopologue has any non-zero ratio values
  # in ratio.negative (0) and/or ratio.positive (1).
  pol.neg <- rowSums(assays.out[["ratio.negative"]] != 0, na.rm = TRUE) > 0
  pol.pos <- rowSums(assays.out[["ratio.positive"]] != 0, na.rm = TRUE) > 0
  polarity <- ifelse(pol.neg & pol.pos, "0;1", ifelse(pol.neg, "0", ifelse(pol.pos, "1", NA_character_)))
  rda.out$polarity <- polarity

  # Cosine similarity of positive vs negative ratio vector per compound, using all
  # isotopologues and all sample.sources (after NA->0 fill).
  cos_sim <- function(a, b) {
    a <- as.numeric(a)
    b <- as.numeric(b)
    den <- sqrt(sum(a * a)) * sqrt(sum(b * b))
    if (!is.finite(den) || den == 0) return(NA_real_)
    sum(a * b) / den
  }
  sim <- rep(NA_real_, nrow(rda.out))
  if ("compound_id" %in% colnames(rda.out)) {
    for (cid in unique(na.omit(as.character(rda.out$compound_id)))) {
      idx <- which(as.character(rda.out$compound_id) == cid)
      if (!length(idx)) next
      a <- assays.out[["ratio.positive"]][idx, , drop = FALSE]
      b <- assays.out[["ratio.negative"]][idx, , drop = FALSE]
      sim_val <- cos_sim(a, b)
      sim[idx] <- sim_val
    }
  }
  rda.out$similarity <- sim

  SummarizedExperiment::SummarizedExperiment(
    assays = assays.out,
    rowData = rda.out,
    colData = cda
  )
}

