#' @title Get MSIP isotopomer probability as SummarizedExperiment
#' @description Extract isotopomer quantification (probabilities) from
#' \code{object@advancedAna$MSIP$isotopomer_data} and return a
#' \code{\link[SummarizedExperiment]{SummarizedExperiment}} with columns as
#' \code{sample.source} and rows as isotopomers.
#'
#' @param object A \code{MSdev} object with \code{object@advancedAna$MSIP$isotopomer_data}
#'   generated by \code{\link{MSIP_get_isotopomer_data}}.
#'
#' @return A \code{SummarizedExperiment} with one assay \code{"probability"}.
#'   \itemize{
#'     \item \code{colData}: \code{sample.source}, \code{group}
#'     \item \code{rowData}: \code{isotopomer_id}, \code{compound_id},
#'       \code{isotopologue_id}, \code{isotopologue_form}, \code{isotopomer_average_mix}
#'   }
#' @export
get_MSIP_Isotopomer_SE <- function(object) {
  `%||%` <- function(a, b) if (!is.null(a)) a else b

  if (is.null(object@advancedAna$MSIP$isotopomer_data)) {
    stop("No MSIP isotopomer data found in object@advancedAna$MSIP$isotopomer_data. ",
         "Run MSIP_get_isotopomer_data() first.")
  }

  isotopomer_data <- object@advancedAna$MSIP$isotopomer_data
  if (!is.list(isotopomer_data) || length(isotopomer_data) == 0) {
    stop("object@advancedAna$MSIP$isotopomer_data is empty.")
  }

  sample.info <- tryCatch({
    as.data.frame(object@sampleInfo)
  }, error = function(e) NULL)

  # Collect all sample sources present in the stored matrices
  sample.sources <- unique(unlist(lapply(isotopomer_data, function(mat) {
    if (is.null(mat)) return(character())
    colnames(mat) %||% character()
  })))
  sample.sources <- as.character(sample.sources)
  if (length(sample.sources) == 0) {
    stop("No sample.source columns found in object@advancedAna$MSIP$isotopomer_data matrices.")
  }

  # colData: sample.source + group (mapped from sample.info if available)
  group.val <- rep(NA_character_, length(sample.sources))
  if (!is.null(sample.info) &&
      nrow(sample.info) > 0 &&
      "sample.source" %in% colnames(sample.info) &&
      "group" %in% colnames(sample.info)) {
    group.val <- vapply(sample.sources, function(ss) {
      g <- unique(as.character(sample.info$group[sample.info$sample.source %in% ss]))
      g <- g[!is.na(g) & nzchar(g)]
      if (length(g) == 0) return(NA_character_)
      paste(g, collapse = ";")
    }, character(1))
  }

  cda <- S4Vectors::DataFrame(
    sample.source = sample.sources,
    group = group.val,
    row.names = sample.sources
  )

  # Helper: get isotopomer meta from a single MSIPCoreData
  .extract_isotopomer_meta <- function(msip.core) {
    if (is.null(msip.core)) return(NULL)
    if (is.null(msip.core@Solve$MSIPIsotopomerMap)) return(NULL)
    im <- msip.core@Solve$MSIPIsotopomerMap
    if (S4Vectors::isEmpty(im)) return(NULL)

    prob <- im@isotopomer.probability
    if (length(prob) == 0) return(NULL)

    iso_names <- names(prob)
    if (is.null(iso_names) || any(!nzchar(iso_names))) {
      iso_names <- paste0("isotopomer_", seq_along(prob))
    }

    sets <- im@solve$isotopomer.set
    if (is.null(sets)) sets <- list()

    isotopomer_mix <- rep(NA_real_, length(iso_names))
    if (length(sets) > 0) {
      set_sizes <- lengths(sets)
      for (set_nm in names(sets)) {
        members <- sets[[set_nm]]
        members <- as.character(members)
        idx <- iso_names %in% members
        if (any(idx)) {
          isotopomer_mix[idx] <- as.numeric(set_sizes[[set_nm]])
        }
      }
    }

    list(
      iso_names = iso_names,
      prob = as.numeric(prob),
      isotopomer_mix = isotopomer_mix
    )
  }

  # Build master row index (compound_id + isotopologue_form + isotopomer name)
  rows <- list()
  for (compound_id in names(isotopomer_data)) {
    mat <- isotopomer_data[[compound_id]]
    if (is.null(mat) || !is.matrix(mat)) next

    iso_forms <- rownames(mat) %||% character()
    for (iso_form in iso_forms) {
      # find one representative msip.core for meta (first non-null)
      msip.core.rep <- NULL
      for (ss in intersect(colnames(mat) %||% character(), sample.sources)) {
        x <- mat[iso_form, ss][[1]]
        if (!is.null(x)) {
          msip.core.rep <- x
          break
        }
      }

      meta <- .extract_isotopomer_meta(msip.core.rep)
      if (is.null(meta)) next

      isotopomer_id <- paste0(compound_id, "_", meta$iso_names)
      isotopologue_id <- paste0(compound_id, "_", iso_form)
      rows[[paste0(compound_id, "::", iso_form)]] <- data.frame(
        isotopomer_id = isotopomer_id,
        compound_id = compound_id,
        isotopologue_id = isotopologue_id,
        isotopologue_form = iso_form,
        iso_name = meta$iso_names,
        stringsAsFactors = FALSE
      )
    }
  }

  if (length(rows) == 0) {
    stop("No solved isotopomer probabilities found in object@advancedAna$MSIP$isotopomer_data.")
  }

  row.df <- do.call(rbind, rows)
  if (anyDuplicated(row.df$isotopomer_id)) {
    warning("Duplicated isotopomer_id detected (same compound_id + isotopomer name across isotopologues). ",
            "Making rownames unique with make.unique().")
    row.df$isotopomer_id <- make.unique(row.df$isotopomer_id)
  }
  rownames(row.df) <- row.df$isotopomer_id

  # assay matrix: probabilities aligned to master rows
  prob.mat <- matrix(NA_real_, nrow = nrow(row.df), ncol = length(sample.sources),
                     dimnames = list(row.df$isotopomer_id, sample.sources))
  mix.mat <- matrix(NA_real_, nrow = nrow(row.df), ncol = length(sample.sources),
                    dimnames = list(row.df$isotopomer_id, sample.sources))

  for (compound_id in names(isotopomer_data)) {
    mat <- isotopomer_data[[compound_id]]
    if (is.null(mat) || !is.matrix(mat)) next
    iso_forms <- rownames(mat) %||% character()

    for (iso_form in iso_forms) {
      for (ss in intersect(colnames(mat) %||% character(), sample.sources)) {
        msip.core <- mat[iso_form, ss][[1]]
        meta <- .extract_isotopomer_meta(msip.core)
        if (is.null(meta)) next

        row_ids <- paste0(compound_id, "_", meta$iso_names)
        keep <- row_ids %in% rownames(prob.mat)
        if (any(keep)) {
          prob.mat[row_ids[keep], ss] <- meta$prob[keep]
          mix.mat[row_ids[keep], ss] <- meta$isotopomer_mix[keep]
        }
      }
    }
  }

  isotopomer_average_mix <- rowMeans(mix.mat, na.rm = TRUE)
  isotopomer_average_mix[is.nan(isotopomer_average_mix)] <- NA_real_

  # keep only requested rowData columns
  rda <- S4Vectors::DataFrame(
    isotopomer_id = row.df$isotopomer_id,
    compound_id = row.df$compound_id,
    isotopologue_id = row.df$isotopologue_id,
    isotopologue_form = row.df$isotopologue_form,
    isotopomer_average_mix = isotopomer_average_mix,
    row.names = row.df$isotopomer_id
  )

  SummarizedExperiment::SummarizedExperiment(
    assays = list(probability = prob.mat),
    rowData = rda,
    colData = cda
  )
}

